### ISSUE TITLE
My Leagues -> When user add a new league then no option is coming on first screen other than 'Other Site'.

### ISSUE THREAD

**Issue by FantasyTesters** [FantasyTesters/Draft-Wizard-Issues#12]
Steps to Reproduce:
1. Launch the app 
2. Login to the app using **Pro users** 
3. Tap on My Leagues
4. Create a League and observe, 

Actual Result: No option is coming for draft take place in case of Pro user.

Expected Result: All the options should be available for user to choose.

Device: All Devices

Build v_1.0 (16)

Video: https://www.dropbox.com/s/r9vub1yye0m7tx3/IMG_3017.MOV?dl=0

**Comment by ahahnsolo** [comment]
Can not confirm.

**Comment by FantasyTesters** [comment]
Not reproducible on latest build v_1.0 (17)
